[tool.poetry]
name = "glances_api"
version = "0.2.2"
description = "Python API for interacting with Glances"
authors = ["Fabian Affolter <fabian@affolter-engineering.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.20.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
pytest = "^6.2.5"
pytest-httpx = "^0.14.0"
pytest-asyncio = "^0.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
